

pipeline {
    agent any
    parameters{
		string(name:'PROJECT_PATH',defaultValue:'sample-projects/Java/calc-app/pom.xml',description:' pom location')         
    }
    tools{
	maven 'M3'        
    }

    stages {
        stage('checkout'){
            steps{
                git 'https://github.com/nagabhushanamn/devops'
            }
        }
        stage('build: compile'){
           steps{
               sh "mvn -f ${params.PROJECT_PATH} clean compile"
           }
        }   
        stage('build: test'){
           steps{
               sh "mvn -f ${params.PROJECT_PATH} test"
           }
        }   
         stage('build: package'){
           steps{
              sh "mvn -f ${params.PROJECT_PATH} clean package"
              archive "${params.PROJECT_PATH}/**/*.jar"
           }
        }   
    }
    post{
        always{
            junit "sample-projects/Java/calc-app/**/surefire-*/TEST-*.xml"
        }
    }

}
    
    