

pipeline {
    agent any
    stages {
        stage('checkout'){
            steps{
                git 'https://github.com/nagabhushanamn/devops'
            }
        }
        stage('build: compile'){
           steps{
               echo 'compile'
           }

        }   
    }
}
    
    